# Generated by Django 4.2.30 on 2026-06-09 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17, unique=True)),
                ('raw_data', models.JSONField()),
                ('risk_score', models.IntegerField()),
                ('accident_count', models.IntegerField(default=0)),
                ('owner_count', models.IntegerField(blank=True, null=True)),
                ('has_salvage_title', models.BooleanField(default=False)),
                ('has_flood_damage', models.BooleanField(default=False)),
                ('open_recall_count', models.IntegerField(default=0)),
                ('last_reported_odometer', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looked_up', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.vehiclereport')),
            ],
            options={
                'ordering': ['-looked_up'],
            },
        ),
    ]
